export declare type UserInfo = {
  id?: number;
  username?: string;
  password?: string;
  icon?: string;
  email?: "xshop@gmail.com";
  nickName?: string;
  tags?: string; //'["Women\'s Fashion"]';
  distributor?: string;
  distributeRatio?: string;
  totalCommission?: string;
  note?: string;  
  createTime?: string; //"2021-04-23T13?:21?:44.000+00?:00";
  loginTime?: string;
  status?: 1 | 0;
  firstName?: string;
  lastName?: string;
  country?: string;
  whatsappNumber?: string;
  age?: number;
  gender?: 'M' | 'F' | '';
  occupation?: string;
  expectEarning?: string;
  currentEarning?: string;
  socialMediaType?: string;
};
